name: Deployment

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: ./scripts/buildprod.sh

    - id: 'auth'
      name: 'Auth to Google'
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials_json: '{{ secrets.GCP_CREDENTIALS }}'
    #     project_id: 'notely-429119'
    #     workload_identity_provider: 'projects/131355886353/locations/global/workloadIdentityPools/github/providers/github'
    #     service_account: 'cloud-run-deployer-99@notely-429119.iam.gserviceaccount.com'
    
    # - run: |-
    #     curl -H 'Bearer: ${{ steps.auth.outputs.access_token }}' https://..

    - name: 'Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Cloud CLI'
      run: 'gcloud info'
    
    - name: Build Docker Image
      run: gcloud builds submit --region=us-central1 --tag us-central1-docker.pkg.dev/notely-429119/notely-ar-repo/ronkiker/notely/latest .



         
    