name: Deployment

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - uses: mscno/setup-goose@v1
    - run: goose up

    - id: 'auth'
      name: 'Auth to Google'
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Cloud CLI'
      run: 'gcloud info'
    
    - name: Build Docker Image
      run: gcloud builds submit --region=us-central1 --tag us-central1-docker.pkg.dev/notely-429119/notely-ar-repo/ronkiker/notely/latest .

    - name: Database migration
      run: ./scripts/migrateup.sh  

    - name: Deploy to Cloud Run
      run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-429119/notely-ar-repo/ronkiker/notely/latest --region us-central1 --allow-unauthenticated --project notely-429119 --max-instances=4


         
    