name: Deployment

on: 
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Setup go
      uses: actions/setup-node@v2
      with:
        go-version: "1.22"

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      run: scripts/buildprod.sh
         